# Data Visualization in Python with Matplotlib, Seaborn, and Streamlit

## 🧩 General Objective
- Learn how to create effective data visualizations using Matplotlib and Seaborn.
- Build a simple web application with Streamlit.
- Upload the project to GitHub to share or deploy it.

| Objective                         | Data Type                              | Recommended Chart Type                      |
|----------------------------------|----------------------------------------|---------------------------------------------|
| Distribution of a variable       | Continuous/Discrete Numerical          | Histogram, KDE, Boxplot                     |
| Compare categories               | Categorical vs. Numerical              | Boxplot, Violinplot, Barplot                |
| Compare values by category       | Nominal Categorical vs. Numerical      | Barplot, Countplot                          |
| Time trends                      | Date + Numerical Variable              | Line plot                                   |
| Correlation between two variables| Two Numerical Variables                | Scatter plot, Heatmap (for many variables)  |
| Cross between two categoricals   | Two Categorical Variables              | Heatmap, Countplot with hue                 |

In [51]:
#!pip install streamlit

Requirement already satisfied: streamlit in c:\users\melor\anaconda3\lib\site-packages (1.44.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (5.3.2)
Requirement already satisfied: click<9,>=7.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (1.24.3)
Requirement already satisfied: packaging<25,>=20 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (24.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (1.5.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (10.2.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (4.25.2)
Requirement already satisfied: pyarrow>=7.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (2.31.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (4.12.1)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (2.1.6)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\melor\anaconda3\lib\site-packages (from streamlit) (6.3.2)
Requirement already satisfied: jinja2 in c:\users\melor\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\melor\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.17.3)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\melor\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.33.0)
Requirement already satisfied: colorama in c:\users\melor\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\melor\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\melor\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\melor\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2022.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\melor\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\melor\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\melor\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\melor\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.2.2)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\melor\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\melor\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\melor\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\melor\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.18.0)
Requirement already satisfied: six>=1.5 in c:\users\melor\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas<3,>=1.4.0->streamlit) (1.16.0)

In [52]:
import streamlit as st

st.title("Mi Primera Aplicación con Streamlit")
st.write("¡Hola mundo!")

# Agregar un widget interactivo
nombre = st.text_input("Escribe tu nombre")
if nombre:
    st.write(f"Hola, {nombre}!")

2025-04-09 01:09:59.992 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.334
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\melor\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-04-09 01:10:00.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.337 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.337 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.339 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.345 Session state does not function when running a script without `streamlit run`
2025-04-09 01:10:00.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:10:00.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [53]:
# Título y texto
st.title("Título de la aplicación")
st.header("Este es un encabezado")
st.subheader("Este es un subencabezado")
st.text("Texto plano")
st.markdown("**Markdown** es _soportado_")

# Widgets interactivos
checkbox_value = st.checkbox("Mostrar gráfico")
option = st.selectbox("Elige una opción", ["Opción 1", "Opción 2"])
slider_value = st.slider("Selecciona un valor", 0, 100)

# Mostrar datos
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10, 3), columns=["A", "B", "C"])
st.dataframe(df)  # Tabla interactiva
st.table(df)      # Tabla estática

# Gráficos
import matplotlib.pyplot as plt

if checkbox_value:
    fig, ax = plt.subplots()
    ax.plot(df)
    st.pyplot(fig)

2025-04-09 01:12:35.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.465 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.467 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.469 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.473 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.475 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.487 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:35.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [54]:
# Columnas
col1, col2 = st.columns(2)
with col1:
    st.header("Columna 1")
    st.write("Contenido de la primera columna")
with col2:
    st.header("Columna 2")
    st.write("Contenido de la segunda columna")

# Pestañas
tab1, tab2 = st.tabs(["Pestaña 1", "Pestaña 2"])
with tab1:
    st.write("Contenido de la pestaña 1")
with tab2:
    st.write("Contenido de la pestaña 2")

# Expander
with st.expander("Haz clic para expandir"):
    st.write("Contenido oculto por defecto")

2025-04-09 01:12:47.860 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.860 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.866 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.870 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.871 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.871 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.874 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.878 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.879 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.891 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-09 01:12:47.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [57]:
!jupyter nbconvert --to script LAB_4_INGLES.ipynb

[NbConvertApp] Converting notebook LAB_4_INGLES.ipynb to script
[NbConvertApp] Writing 21045 bytes to LAB_4_INGLES.py

## 1. Quantities: 
This type of graph shows the levels of variables. Also, these graphs show the variables according to categories or classifications.

Datasets transformed into Latin characters. The following commands should be used in STATA:

cd "....\documents"

unicode analyze enaho.dta

unicode encoding set "latin1" 

unicode translate enaho.dta

In [58]:
enaho = pd.read_stata(r"../_data/enaho.dta")
enaho

FileNotFoundError: [Errno 2] No such file or directory: '../_data/enaho.dta'

#### We will explore the BCRP data using the codes of its variables.

In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
# Configurar Selenium (ajusta la ruta del driver)
driver = webdriver.Chrome()
driver.maximize_window()


# URL de la página que contiene los datos
url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/mensuales/"  
driver.get(url)

# Esperar carga

In [3]:
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

In [4]:
# Esperar hasta que el input esté listo (máx 10 segundos)
wait = WebDriverWait(driver, 10)
search_box = wait.until(EC.presence_of_element_located((By.ID, "txtbuscador")))

search_box.click()
search_box.send_keys("PN01449BM")
search_box.send_keys(Keys.ENTER)  # Opcional: para simular Enter

In [5]:
wait = WebDriverWait(driver, 10)
link_element = wait.until(EC.presence_of_element_located((By.XPATH, "//a[contains(@href, '/estadisticas/series/mensuales/resultados/') and contains(@href, 'html')]")))

# Hacer clic en el enlace
link_element.click()

In [19]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException

def extraer_datos_bcrp(codigo_serie):
    # Iniciar el navegador
    driver = webdriver.Chrome()
    driver.maximize_window()
    
    try:
        # Acceder directamente al enlace con el código proporcionado
        url = f"https://estadisticas.bcrp.gob.pe/estadisticas/series/mensuales/resultados/{codigo_serie}/html"
        driver.get(url)

        # Esperar que la tabla cargue
        wait = WebDriverWait(driver, 10)
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'table.series')))

        # Extraer filas de la tabla
        rows = driver.find_elements(By.CSS_SELECTOR, 'table.series tbody tr')
        data = []

        for row in rows:
            try:
                periodo_elem = row.find_element(By.CSS_SELECTOR, 'td.periodo b')
                dato_elem = row.find_element(By.CSS_SELECTOR, 'td.dato')

                periodo = periodo_elem.text.strip()
                dato = dato_elem.text.strip()
                data.append((periodo, dato))
            except NoSuchElementException:
                continue  # Saltar filas sin datos
        
        return data

    except TimeoutException:
        print("La página tardó demasiado en cargar o el código es inválido.")
        return []

    finally:
        driver.quit()

In [29]:
import pandas as pd

codigo = "RD38085BM"
datos = extraer_datos_bcrp(codigo)

# Crear el DataFrame con nombres de columnas
df = pd.DataFrame(datos, columns=['Periodo', 'Dato'])

# Convertir la columna 'Dato' a numérico
df['Dato'] = pd.to_numeric(df['Dato'], errors='coerce')

print(df)

    Periodo  Dato
0     Ene05     0
1     Feb05     0
2     Mar05     0
3     Abr05     0
4     May05     0
..      ...   ...
211   Ago22     9
212   Sep22    12
213   Oct22    11
214   Nov22     5
215   Dic22     6

[216 rows x 2 columns]

In [30]:
from datetime import datetime
from dateutil.relativedelta import relativedelta

def generar_fechas_bcrp(inicio, fin, como_datetime=False):
    """
    Genera una lista de fechas mensuales desde un período inicial hasta uno final.
    
    Args:
        inicio (str): Periodo inicial en formato BCRP (Ej: "Ene85")
        fin (str): Periodo final en formato BCRP (Ej: "Dic23")
        como_datetime (bool): Si True, retorna objetos datetime. Si False, retorna strings "YYYY-MM".

    Returns:
        List[str] o List[datetime]: Lista de fechas mensuales.
    """
    # Mapear los meses en español a números
    meses = {
        "Ene": 1, "Feb": 2, "Mar": 3, "Abr": 4,
        "May": 5, "Jun": 6, "Jul": 7, "Ago": 8,
        "Set": 9, "Oct": 10, "Nov": 11, "Dic": 12
    }

    def convertir_periodo(periodo):
        mes_str = periodo[:3]
        anio_str = periodo[3:]

        mes = meses[mes_str]
        anio = int(anio_str)
        if anio < 100:
            anio += 1900 if anio >= 50 else 2000  # 2 dígitos a 4

        return datetime(anio, mes, 1)

    fecha_inicio = convertir_periodo(inicio)
    fecha_fin = convertir_periodo(fin)

    fechas = []
    actual = fecha_inicio

    while actual <= fecha_fin:
        if como_datetime:
            fechas.append(actual)
        else:
            fechas.append(actual.strftime("%Y-%m"))  # o "%Y-%m-%d" si prefieres el día
        actual += relativedelta(months=1)

    return fechas

In [40]:
fechas_dt = generar_fechas_bcrp("Ene05", "Dic22", como_datetime=True)
fechas_dt = pd.DataFrame(fechas_dt, columns=['Fecha'])
print(fechas_dt.dtypes)
fechas_dt

Fecha    datetime64[ns]
dtype: object

         Fecha
0   2005-01-01
1   2005-02-01
2   2005-03-01
3   2005-04-01
4   2005-05-01
..         ...
211 2022-08-01
212 2022-09-01
213 2022-10-01
214 2022-11-01
215 2022-12-01

[216 rows x 1 columns]

In [33]:
df = df.drop(columns=['Periodo'], axis =0)
df

     Dato
0       0
1       0
2       0
3       0
4       0
..    ...
211     9
212    12
213    11
214     5
215     6

[216 rows x 1 columns]

In [34]:
df.set_index('fechas_dt', inplace=True)

KeyError: "None of ['fechas_dt'] are in the columns"

In [28]:
df

     Dato
0       0
1       0
2       0
3       0
4       0
..    ...
211     9
212    12
213    11
214     5
215     6

[216 rows x 1 columns]

In [41]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import pandas as pd
import time
import os

def extraer_datos_bcrp(codigos_dict):
    """
    Extrae datos del BCRP para múltiples códigos
    
    Args:
        codigos_dict: Diccionario con formato {codigo: descripcion}
    
    Returns:
        Un diccionario con los datos extraídos por cada región
    """
    # Configuración del navegador
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')  # Opcional: ejecutar sin interfaz gráfica
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()
    
    resultados = {}
    
    try:
        for codigo, descripcion in codigos_dict.items():
            print(f"Procesando {descripcion} (código: {codigo})...")
            
            # Acceder directamente al enlace con el código proporcionado
            url = f"https://estadisticas.bcrp.gob.pe/estadisticas/series/mensuales/resultados/{codigo}/html"
            driver.get(url)
            
            try:
                # Esperar que la tabla cargue
                wait = WebDriverWait(driver, 10)
                wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'table.series')))
                
                # Extraer filas de la tabla
                rows = driver.find_elements(By.CSS_SELECTOR, 'table.series tbody tr')
                data = []
                
                for row in rows:
                    try:
                        periodo_elem = row.find_element(By.CSS_SELECTOR, 'td.periodo b')
                        dato_elem = row.find_element(By.CSS_SELECTOR, 'td.dato')
                        periodo = periodo_elem.text.strip()
                        dato = dato_elem.text.strip()
                        data.append((periodo, dato))
                    except NoSuchElementException:
                        continue  # Saltar filas sin datos
                
                resultados[descripcion] = data
                print(f"✓ Datos extraídos correctamente para {descripcion}")
                
                # Pausa breve para no sobrecargar el servidor
                time.sleep(1)
                
            except TimeoutException:
                print(f"❌ Error: Timeout al cargar datos para {descripcion} (código: {codigo})")
                resultados[descripcion] = []
    
    except Exception as e:
        print(f"Error general: {str(e)}")
    
    finally:
        driver.quit()
        
    return resultados

def guardar_resultados(resultados, formato="csv"):
    """
    Guarda los resultados en archivos
    
    Args:
        resultados: Diccionario con los datos extraídos
        formato: 'csv' o 'excel'
    """
    # Crear directorio para resultados si no existe
    os.makedirs("resultados_bcrp", exist_ok=True)
    
    # Guardar cada región en un archivo separado
    for region, datos in resultados.items():
        if not datos:
            print(f"No hay datos para guardar de {region}")
            continue
            
        df = pd.DataFrame(datos, columns=['Periodo', 'Valor'])
        
        # Limpiar el nombre del archivo
        nombre_archivo = region.replace("/", "_").replace("\\", "_").strip()
        
        if formato == "csv":
            ruta = f"resultados_bcrp/{nombre_archivo}.csv"
            df.to_csv(ruta, index=False)
        elif formato == "excel":
            ruta = f"resultados_bcrp/{nombre_archivo}.xlsx"
            df.to_excel(ruta, index=False)
            
        print(f"Archivo guardado: {ruta}")
    
    # Crear un archivo consolidado con todos los datos
    all_data = []
    
    for region, datos in resultados.items():
        if datos:
            for periodo, valor in datos:
                all_data.append((region, periodo, valor))
    
    if all_data:
        df_consolidado = pd.DataFrame(all_data, columns=['Region', 'Periodo', 'Valor'])
        
        if formato == "csv":
            df_consolidado.to_csv("resultados_bcrp/consolidado.csv", index=False)
        elif formato == "excel":
            df_consolidado.to_excel("resultados_bcrp/consolidado.xlsx", index=False)
            
        print(f"Archivo consolidado guardado en resultados_bcrp/consolidado.{formato}")

# Códigos y descripciones proporcionados
codigos_bcrp = {
    "RD38085BM": "Amazonas",
    "RD38086BM": "Ancash",
    "RD38087BM": "Apurimac",
    "RD38088BM": "Arequipa",
    "RD38089BM": "Ayacucho",
    "RD38090BM": "Cajamarca",
    "RD38091BM": "Callao",
    "RD38092BM": "Cusco",
    "RD38093BM": "Huancavelica",
    "RD38094BM": "Huánuco",
    "RD38095BM": "Ica",
    "RD38096BM": "Junín",
    "RD38097BM": "La Libertad",
    "RD38098BM": "Lambayeque",
    "RD38099BM": "Lima",
    "RD38100BM": "Loreto",
    "RD38101BM": "Madre de Dios",
    "RD38102BM": "Moquegua",
    "RD38103BM": "Pasco",
    "RD38104BM": "Piura",
    "RD38105BM": "Puno",
    "RD38106BM": "San Martín",
    "RD38107BM": "Tacna",
    "RD38108BM": "Tumbes",
    "RD38109BM": "Ucayali",
    "RD38110BM": "No registrado",
    "RD38111BM": "Total"
}

# Ejecutar el script
if __name__ == "__main__":
    print("Iniciando extracción de datos del BCRP...")
    resultados = extraer_datos_bcrp(codigos_bcrp)
    
    # Guardar resultados en CSV (puedes cambiar a "excel" si prefieres)
    guardar_resultados(resultados, formato="csv")
    
    print("Proceso completado.")

Iniciando extracción de datos del BCRP...
Procesando Amazonas (código: RD38085BM)...
✓ Datos extraídos correctamente para Amazonas
Procesando Ancash (código: RD38086BM)...
✓ Datos extraídos correctamente para Ancash
Procesando Apurimac (código: RD38087BM)...
✓ Datos extraídos correctamente para Apurimac
Procesando Arequipa (código: RD38088BM)...
✓ Datos extraídos correctamente para Arequipa
Procesando Ayacucho (código: RD38089BM)...
✓ Datos extraídos correctamente para Ayacucho
Procesando Cajamarca (código: RD38090BM)...
✓ Datos extraídos correctamente para Cajamarca
Procesando Callao (código: RD38091BM)...
✓ Datos extraídos correctamente para Callao
Procesando Cusco (código: RD38092BM)...
✓ Datos extraídos correctamente para Cusco
Procesando Huancavelica (código: RD38093BM)...
✓ Datos extraídos correctamente para Huancavelica
Procesando Huánuco (código: RD38094BM)...
✓ Datos extraídos correctamente para Huánuco
Procesando Ica (código: RD38095BM)...
✓ Datos extraídos correctamente para Ica
Procesando Junín (código: RD38096BM)...
✓ Datos extraídos correctamente para Junín
Procesando La Libertad (código: RD38097BM)...
✓ Datos extraídos correctamente para La Libertad
Procesando Lambayeque (código: RD38098BM)...
✓ Datos extraídos correctamente para Lambayeque
Procesando Lima (código: RD38099BM)...
✓ Datos extraídos correctamente para Lima
Procesando Loreto (código: RD38100BM)...
✓ Datos extraídos correctamente para Loreto
Procesando Madre de Dios (código: RD38101BM)...
✓ Datos extraídos correctamente para Madre de Dios
Procesando Moquegua (código: RD38102BM)...
✓ Datos extraídos correctamente para Moquegua
Procesando Pasco (código: RD38103BM)...
✓ Datos extraídos correctamente para Pasco
Procesando Piura (código: RD38104BM)...
✓ Datos extraídos correctamente para Piura
Procesando Puno (código: RD38105BM)...
✓ Datos extraídos correctamente para Puno
Procesando San Martín (código: RD38106BM)...
✓ Datos extraídos correctamente para San Martín
Procesando Tacna (código: RD38107BM)...
✓ Datos extraídos correctamente para Tacna
Procesando Tumbes (código: RD38108BM)...
✓ Datos extraídos correctamente para Tumbes
Procesando Ucayali (código: RD38109BM)...
✓ Datos extraídos correctamente para Ucayali
Procesando No registrado (código: RD38110BM)...
✓ Datos extraídos correctamente para No registrado
Procesando Total (código: RD38111BM)...
✓ Datos extraídos correctamente para Total
Archivo guardado: resultados_bcrp/Amazonas.csv
Archivo guardado: resultados_bcrp/Ancash.csv
Archivo guardado: resultados_bcrp/Apurimac.csv
Archivo guardado: resultados_bcrp/Arequipa.csv
Archivo guardado: resultados_bcrp/Ayacucho.csv
Archivo guardado: resultados_bcrp/Cajamarca.csv
Archivo guardado: resultados_bcrp/Callao.csv
Archivo guardado: resultados_bcrp/Cusco.csv
Archivo guardado: resultados_bcrp/Huancavelica.csv
Archivo guardado: resultados_bcrp/Huánuco.csv
Archivo guardado: resultados_bcrp/Ica.csv
Archivo guardado: resultados_bcrp/Junín.csv
Archivo guardado: resultados_bcrp/La Libertad.csv
Archivo guardado: resultados_bcrp/Lambayeque.csv
Archivo guardado: resultados_bcrp/Lima.csv
Archivo guardado: resultados_bcrp/Loreto.csv
Archivo guardado: resultados_bcrp/Madre de Dios.csv
Archivo guardado: resultados_bcrp/Moquegua.csv
Archivo guardado: resultados_bcrp/Pasco.csv
Archivo guardado: resultados_bcrp/Piura.csv
Archivo guardado: resultados_bcrp/Puno.csv
Archivo guardado: resultados_bcrp/San Martín.csv
Archivo guardado: resultados_bcrp/Tacna.csv
Archivo guardado: resultados_bcrp/Tumbes.csv
Archivo guardado: resultados_bcrp/Ucayali.csv
Archivo guardado: resultados_bcrp/No registrado.csv
Archivo guardado: resultados_bcrp/Total.csv
Archivo consolidado guardado en resultados_bcrp/consolidado.csv
Proceso completado.

In [46]:
resultados

{'Amazonas': [('Ene05', '0'),
  ('Feb05', '0'),
  ('Mar05', '0'),
  ('Abr05', '0'),
  ('May05', '0'),
  ('Jun05', '0'),
  ('Jul05', '0'),
  ('Ago05', '0'),
  ('Sep05', '0'),
  ('Oct05', '0'),
  ('Nov05', '3'),
  ('Dic05', '0'),
  ('Ene06', '0'),
  ('Feb06', '0'),
  ('Mar06', '0'),
  ('Abr06', '0'),
  ('May06', '0'),
  ('Jun06', '0'),
  ('Jul06', '1'),
  ('Ago06', '1'),
  ('Sep06', '1'),
  ('Oct06', '1'),
  ('Nov06', '1'),
  ('Dic06', '1'),
  ('Ene07', '0'),
  ('Feb07', '0'),
  ('Mar07', '0'),
  ('Abr07', '0'),
  ('May07', '0'),
  ('Jun07', '0'),
  ('Jul07', '0'),
  ('Ago07', '1'),
  ('Sep07', '1'),
  ('Oct07', '0'),
  ('Nov07', '1'),
  ('Dic07', '8'),
  ('Ene08', '0'),
  ('Feb08', '0'),
  ('Mar08', '0'),
  ('Abr08', '0'),
  ('May08', '0'),
  ('Jun08', '0'),
  ('Jul08', '0'),
  ('Ago08', '2'),
  ('Sep08', '2'),
  ('Oct08', '1'),
  ('Nov08', '1'),
  ('Dic08', '0'),
  ('Ene09', '1'),
  ('Feb09', '0'),
  ('Mar09', '0'),
  ('Abr09', '0'),
  ('May09', '0'),
  ('Jun09', '1'),
  ('Jul09', '1'),
  ('Ago09', '2'),
  ('Sep09', '2'),
  ('Oct09', '1'),
  ('Nov09', '1'),
  ('Dic09', '2'),
  ('Ene10', '0'),
  ('Feb10', '0'),
  ('Mar10', '0'),
  ('Abr10', '0'),
  ('May10', '0'),
  ('Jun10', '0'),
  ('Jul10', '2'),
  ('Ago10', '2'),
  ('Sep10', '3'),
  ('Oct10', '3'),
  ('Nov10', '2'),
  ('Dic10', '2'),
  ('Ene11', '1'),
  ('Feb11', '1'),
  ('Mar11', '0'),
  ('Abr11', '0'),
  ('May11', '0'),
  ('Jun11', '2'),
  ('Jul11', '2'),
  ('Ago11', '1'),
  ('Sep11', '6'),
  ('Oct11', '2'),
  ('Nov11', '3'),
  ('Dic11', '3'),
  ('Ene12', '2'),
  ('Feb12', '0'),
  ('Mar12', '0'),
  ('Abr12', '0'),
  ('May12', '0'),
  ('Jun12', '1'),
  ('Jul12', '2'),
  ('Ago12', '4'),
  ('Sep12', '2'),
  ('Oct12', '3'),
  ('Nov12', '2'),
  ('Dic12', '3'),
  ('Ene13', '1'),
  ('Feb13', '1'),
  ('Mar13', '0'),
  ('Abr13', '1'),
  ('May13', '1'),
  ('Jun13', '2'),
  ('Jul13', '2'),
  ('Ago13', '2'),
  ('Sep13', '1'),
  ('Oct13', '1'),
  ('Nov13', '1'),
  ('Dic13', '1'),
  ('Ene14', '0'),
  ('Feb14', '0'),
  ('Mar14', '0'),
  ('Abr14', '1'),
  ('May14', '0'),
  ('Jun14', '0'),
  ('Jul14', '0'),
  ('Ago14', '0'),
  ('Sep14', '0'),
  ('Oct14', '0'),
  ('Nov14', '1'),
  ('Dic14', '1'),
  ('Ene15', '0'),
  ('Feb15', '1'),
  ('Mar15', '0'),
  ('Abr15', '0'),
  ('May15', '0'),
  ('Jun15', '0'),
  ('Jul15', '1'),
  ('Ago15', '1'),
  ('Sep15', '2'),
  ('Oct15', '1'),
  ('Nov15', '2'),
  ('Dic15', '1'),
  ('Ene16', '1'),
  ('Feb16', '1'),
  ('Mar16', '0'),
  ('Abr16', '0'),
  ('May16', '0'),
  ('Jun16', '1'),
  ('Jul16', '3'),
  ('Ago16', '4'),
  ('Sep16', '6'),
  ('Oct16', '7'),
  ('Nov16', '5'),
  ('Dic16', '5'),
  ('Ene17', '2'),
  ('Feb17', '1'),
  ('Mar17', '0'),
  ('Abr17', '0'),
  ('May17', '1'),
  ('Jun17', '3'),
  ('Jul17', '2'),
  ('Ago17', '6'),
  ('Sep17', '4'),
  ('Oct17', '4'),
  ('Nov17', '7'),
  ('Dic17', '4'),
  ('Ene18', '2'),
  ('Feb18', '2'),
  ('Mar18', '1'),
  ('Abr18', '0'),
  ('May18', '1'),
  ('Jun18', '3'),
  ('Jul18', '4'),
  ('Ago18', '4'),
  ('Sep18', '5'),
  ('Oct18', '7'),
  ('Nov18', '5'),
  ('Dic18', '4'),
  ('Ene19', '2'),
  ('Feb19', '2'),
  ('Mar19', '0'),
  ('Abr19', '1'),
  ('May19', '1'),
  ('Jun19', '3'),
  ('Jul19', '4'),
  ('Ago19', '4'),
  ('Sep19', '5'),
  ('Oct19', '5'),
  ('Nov19', '4'),
  ('Dic19', '5'),
  ('Ene20', '1'),
  ('Feb20', '0'),
  ('Mar20', '0'),
  ('Abr20', '1'),
  ('May20', '1'),
  ('Jun20', '1'),
  ('Jul20', '3'),
  ('Ago20', '7'),
  ('Sep20', '7'),
  ('Oct20', '10'),
  ('Nov20', '4'),
  ('Dic20', '5'),
  ('Ene21', '3'),
  ('Feb21', '1'),
  ('Mar21', '1'),
  ('Abr21', '1'),
  ('May21', '2'),
  ('Jun21', '2'),
  ('Jul21', '5'),
  ('Ago21', '5'),
  ('Sep21', '8'),
  ('Oct21', '6'),
  ('Nov21', '4'),
  ('Dic21', '6'),
  ('Ene22', '5'),
  ('Feb22', '4'),
  ('Mar22', '2'),
  ('Abr22', '1'),
  ('May22', '2'),
  ('Jun22', '4'),
  ('Jul22', '5'),
  ('Ago22', '9'),
  ('Sep22', '12'),
  ('Oct22', '11'),
  ('Nov22', '5'),
  ('Dic22', '6')],
 'Ancash': [('Ene05', '189'),
  ('Feb05', '152'),
  ('Mar05', '198'),
  ('Abr05', '157'),
  ('May05', '188'),
  ('Jun05', '231'),
  ('Jul05', '241'),
  ('Ago05', '209'),
  ('Sep05', '215'),
  ('Oct05', '188'),
  ('Nov05', '223'),
  ('Dic05', '315'),
  ('Ene06', '198'),
  ('Feb06', '232'),
  ('Mar06', '272'),
  ('Abr06', '270'),
  ('May06', '251'),
  ('Jun06', '320'),
  ('Jul06', '390'),
  ('Ago06', '411'),
  ('Sep06', '280'),
  ('Oct06', '311'),
  ('Nov06', '346'),
  ('Dic06', '397'),
  ('Ene07', '195'),
  ('Feb07', '297'),
  ('Mar07', '335'),
  ('Abr07', '280'),
  ('May07', '353'),
  ('Jun07', '301'),
  ('Jul07', '418'),
  ('Ago07', '437'),
  ('Sep07', '302'),
  ('Oct07', '413'),
  ('Nov07', '296'),
  ('Dic07', '381'),
  ('Ene08', '308'),
  ('Feb08', '245'),
  ('Mar08', '381'),
  ('Abr08', '458'),
  ('May08', '500'),
  ('Jun08', '416'),
  ('Jul08', '463'),
  ('Ago08', '331'),
  ('Sep08', '275'),
  ('Oct08', '236'),
  ('Nov08', '172'),
  ('Dic08', '188'),
  ('Ene09', '168'),
  ('Feb09', '176'),
  ('Mar09', '211'),
  ('Abr09', '154'),
  ('May09', '218'),
  ('Jun09', '275'),
  ('Jul09', '263'),
  ('Ago09', '257'),
  ('Sep09', '268'),
  ('Oct09', '255'),
  ('Nov09', '260'),
  ('Dic09', '412'),
  ('Ene10', '249'),
  ('Feb10', '282'),
  ('Mar10', '303'),
  ('Abr10', '312'),
  ('May10', '238'),
  ('Jun10', '303'),
  ('Jul10', '457'),
  ('Ago10', '280'),
  ('Sep10', '457'),
  ('Oct10', '327'),
  ('Nov10', '322'),
  ('Dic10', '362'),
  ('Ene11', '353'),
  ('Feb11', '433'),
  ('Mar11', '396'),
  ('Abr11', '283'),
  ('May11', '368'),
  ('Jun11', '413'),
  ('Jul11', '414'),
  ('Ago11', '408'),
  ('Sep11', '385'),
  ('Oct11', '339'),
  ('Nov11', '248'),
  ('Dic11', '456'),
  ('Ene12', '419'),
  ('Feb12', '394'),
  ('Mar12', '455'),
  ('Abr12', '316'),
  ('May12', '418'),
  ('Jun12', '388'),
  ('Jul12', '514'),
  ('Ago12', '409'),
  ('Sep12', '385'),
  ('Oct12', '555'),
  ('Nov12', '443'),
  ('Dic12', '353'),
  ('Ene13', '247'),
  ('Feb13', '250'),
  ('Mar13', '329'),
  ('Abr13', '242'),
  ('May13', '335'),
  ('Jun13', '364'),
  ('Jul13', '365'),
  ('Ago13', '579'),
  ('Sep13', '425'),
  ('Oct13', '380'),
  ('Nov13', '369'),
  ('Dic13', '433'),
  ('Ene14', '309'),
  ('Feb14', '371'),
  ('Mar14', '359'),
  ('Abr14', '227'),
  ('May14', '218'),
  ('Jun14', '253'),
  ('Jul14', '246'),
  ('Ago14', '309'),
  ('Sep14', '211'),
  ('Oct14', '273'),
  ('Nov14', '244'),
  ('Dic14', '264'),
  ('Ene15', '189'),
  ('Feb15', '208'),
  ('Mar15', '201'),
  ('Abr15', '156'),
  ('May15', '223'),
  ('Jun15', '302'),
  ('Jul15', '229'),
  ('Ago15', '302'),
  ('Sep15', '189'),
  ('Oct15', '269'),
  ('Nov15', '242'),
  ('Dic15', '255'),
  ('Ene16', '134'),
  ('Feb16', '224'),
  ('Mar16', '216'),
  ('Abr16', '277'),
  ('May16', '249'),
  ('Jun16', '200'),
  ('Jul16', '219'),
  ('Ago16', '220'),
  ('Sep16', '254'),
  ('Oct16', '256'),
  ('Nov16', '167'),
  ('Dic16', '260'),
  ('Ene17', '249'),
  ('Feb17', '316'),
  ('Mar17', '296'),
  ('Abr17', '297'),
  ('May17', '278'),
  ('Jun17', '372'),
  ('Jul17', '234'),
  ('Ago17', '260'),
  ('Sep17', '396'),
  ('Oct17', '267'),
  ('Nov17', '344'),
  ('Dic17', '445'),
  ('Ene18', '311'),
  ('Feb18', '334'),
  ('Mar18', '415'),
  ('Abr18', '386'),
  ('May18', '469'),
  ('Jun18', '469'),
  ('Jul18', '442'),
  ('Ago18', '393'),
  ('Sep18', '312'),
  ('Oct18', '272'),
  ('Nov18', '349'),
  ('Dic18', '402'),
  ('Ene19', '274'),
  ('Feb19', '329'),
  ('Mar19', '394'),
  ('Abr19', '360'),
  ('May19', '335'),
  ('Jun19', '292'),
  ('Jul19', '307'),
  ('Ago19', '310'),
  ('Sep19', '283'),
  ('Oct19', '344'),
  ('Nov19', '252'),
  ('Dic19', '417'),
  ('Ene20', '311'),
  ('Feb20', '301'),
  ('Mar20', '300'),
  ('Abr20', '183'),
  ('May20', '45'),
  ('Jun20', '228'),
  ('Jul20', '344'),
  ('Ago20', '418'),
  ('Sep20', '390'),
  ('Oct20', '433'),
  ('Nov20', '421'),
  ('Dic20', '533'),
  ('Ene21', '419'),
  ('Feb21', '550'),
  ('Mar21', '640'),
  ('Abr21', '512'),
  ('May21', '515'),
  ('Jun21', '560'),
  ('Jul21', '516'),
  ('Ago21', '591'),
  ('Sep21', '530'),
  ('Oct21', '450'),
  ('Nov21', '628'),
  ('Dic21', '721'),
  ('Ene22', '373'),
  ('Feb22', '567'),
  ('Mar22', '570'),
  ('Abr22', '469'),
  ('May22', '421'),
  ('Jun22', '465'),
  ('Jul22', '428'),
  ('Ago22', '662'),
  ('Sep22', '594'),
  ('Oct22', '422'),
  ('Nov22', '482'),
  ('Dic22', '454')],
 'Apurimac': [('Ene05', '0'),
  ('Feb05', '0'),
  ('Mar05', '5'),
  ('Abr05', '3'),
  ('May05', '4'),
  ('Jun05', '0'),
  ('Jul05', '3'),
  ('Ago05', '3'),
  ('Sep05', '4'),
  ('Oct05', '3'),
  ('Nov05', '0'),
  ('Dic05', '7'),
  ('Ene06', '0'),
  ('Feb06', '0'),
  ('Mar06', '21'),
  ('Abr06', '0'),
  ('May06', '20'),
  ('Jun06', '0'),
  ('Jul06', '20'),
  ('Ago06', '0'),
  ('Sep06', '0'),
  ('Oct06', '24'),
  ('Nov06', '0'),
  ('Dic06', '20'),
  ('Ene07', '0'),
  ('Feb07', '0'),
  ('Mar07', '0'),
  ('Abr07', '0'),
  ('May07', '0'),
  ('Jun07', '0'),
  ('Jul07', '0'),
  ('Ago07', '0'),
  ('Sep07', '0'),
  ('Oct07', '0'),
  ('Nov07', '5'),
  ('Dic07', '3'),
  ('Ene08', '0'),
  ('Feb08', '5'),
  ('Mar08', '4'),
  ('Abr08', '4'),
  ('May08', '0'),
  ('Jun08', '8'),
  ('Jul08', '11'),
  ('Ago08', '3'),
  ('Sep08', '6'),
  ('Oct08', '0'),
  ('Nov08', '5'),
  ('Dic08', '13'),
  ('Ene09', '0'),
  ('Feb09', '6'),
  ('Mar09', '0'),
  ('Abr09', '4'),
  ('May09', '7'),
  ('Jun09', '0'),
  ('Jul09', '50'),
  ('Ago09', '7'),
  ('Sep09', '25'),
  ('Oct09', '8'),
  ('Nov09', '0'),
  ('Dic09', '11'),
  ('Ene10', '8'),
  ('Feb10', '10'),
  ('Mar10', '0'),
  ('Abr10', '14'),
  ('May10', '6'),
  ('Jun10', '10'),
  ('Jul10', '12'),
  ('Ago10', '8'),
  ('Sep10', '3'),
  ('Oct10', '9'),
  ('Nov10', '16'),
  ('Dic10', '24'),
  ('Ene11', '0'),
  ('Feb11', '0'),
  ('Mar11', '1'),
  ('Abr11', '2'),
  ('May11', '0'),
  ('Jun11', '6'),
  ('Jul11', '0'),
  ('Ago11', '0'),
  ('Sep11', '3'),
  ('Oct11', '0'),
  ('Nov11', '3'),
  ('Dic11', '8'),
  ('Ene12', '6'),
  ('Feb12', '10'),
  ('Mar12', '5'),
  ('Abr12', '0'),
  ('May12', '5'),
  ('Jun12', '6'),
  ('Jul12', '15'),
  ('Ago12', '7'),
  ('Sep12', '7'),
  ('Oct12', '11'),
  ('Nov12', '7'),
  ('Dic12', '8'),
  ('Ene13', '5'),
  ('Feb13', '7'),
  ('Mar13', '0'),
  ('Abr13', '9'),
  ('May13', '4'),
  ('Jun13', '4'),
  ('Jul13', '1'),
  ('Ago13', '0'),
  ('Sep13', '4'),
  ('Oct13', '4'),
  ('Nov13', '5'),
  ('Dic13', '4'),
  ('Ene14', '0'),
  ('Feb14', '4'),
  ('Mar14', '7'),
  ('Abr14', '4'),
  ('May14', '0'),
  ('Jun14', '4'),
  ('Jul14', '4'),
  ('Ago14', '3'),
  ('Sep14', '2'),
  ('Oct14', '3'),
  ('Nov14', '3'),
  ('Dic14', '0'),
  ('Ene15', '3'),
  ('Feb15', '0'),
  ('Mar15', '2'),
  ('Abr15', '5'),
  ('May15', '2'),
  ('Jun15', '2'),
  ('Jul15', '9'),
  ('Ago15', '8'),
  ('Sep15', '10'),
  ('Oct15', '14'),
  ('Nov15', '13'),
  ('Dic15', '7'),
  ('Ene16', '43'),
  ('Feb16', '38'),
  ('Mar16', '55'),
  ('Abr16', '73'),
  ('May16', '102'),
  ('Jun16', '48'),
  ('Jul16', '182'),
  ('Ago16', '73'),
  ('Sep16', '124'),
  ('Oct16', '222'),
  ('Nov16', '240'),
  ('Dic16', '339'),
  ('Ene17', '242'),
  ('Feb17', '276'),
  ('Mar17', '223'),
  ('Abr17', '143'),
  ('May17', '239'),
  ('Jun17', '216'),
  ('Jul17', '161'),
  ('Ago17', '275'),
  ('Sep17', '278'),
  ('Oct17', '241'),
  ('Nov17', '377'),
  ('Dic17', '172'),
  ('Ene18', '299'),
  ('Feb18', '189'),
  ('Mar18', '199'),
  ('Abr18', '156'),
  ('May18', '258'),
  ('Jun18', '238'),
  ('Jul18', '191'),
  ('Ago18', '149'),
  ('Sep18', '183'),
  ('Oct18', '158'),
  ('Nov18', '282'),
  ('Dic18', '277'),
  ('Ene19', '189'),
  ('Feb19', '72'),
  ('Mar19', '2'),
  ('Abr19', '98'),
  ('May19', '264'),
  ('Jun19', '206'),
  ('Jul19', '158'),
  ('Ago19', '171'),
  ('Sep19', '165'),
  ('Oct19', '73'),
  ('Nov19', '122'),
  ('Dic19', '417'),
  ('Ene20', '226'),
  ('Feb20', '134'),
  ('Mar20', '144'),
  ('Abr20', '2'),
  ('May20', '96'),
  ('Jun20', '249'),
  ('Jul20', '190'),
  ('Ago20', '28'),
  ('Sep20', '290'),
  ('Oct20', '281'),
  ('Nov20', '267'),
  ('Dic20', '147'),
  ('Ene21', '146'),
  ('Feb21', '299'),
  ('Mar21', '335'),
  ('Abr21', '135'),
  ('May21', '529'),
  ('Jun21', '395'),
  ('Jul21', '228'),
  ('Ago21', '321'),
  ('Sep21', '216'),
  ('Oct21', '154'),
  ('Nov21', '252'),
  ('Dic21', '33'),
  ('Ene22', '175'),
  ('Feb22', '166'),
  ('Mar22', '7'),
  ('Abr22', '304'),
  ('May22', '35'),
  ('Jun22', '188'),
  ('Jul22', '249'),
  ('Ago22', '312'),
  ('Sep22', '272'),
  ('Oct22', '263'),
  ('Nov22', '40'),
  ('Dic22', '44')],
 'Arequipa': [('Ene05', '28'),
  ('Feb05', '31'),
  ('Mar05', '57'),
  ('Abr05', '56'),
  ('May05', '56'),
  ('Jun05', '41'),
  ('Jul05', '59'),
  ('Ago05', '51'),
  ('Sep05', '48'),
  ('Oct05', '22'),
  ('Nov05', '82'),
  ('Dic05', '52'),
  ('Ene06', '39'),
  ('Feb06', '43'),
  ('Mar06', '29'),
  ('Abr06', '108'),
  ('May06', '61'),
  ('Jun06', '82'),
  ('Jul06', '77'),
  ('Ago06', '22'),
  ('Sep06', '141'),
  ('Oct06', '89'),
  ('Nov06', '70'),
  ('Dic06', '72'),
  ('Ene07', '89'),
  ('Feb07', '109'),
  ('Mar07', '161'),
  ('Abr07', '142'),
  ('May07', '112'),
  ('Jun07', '234'),
  ('Jul07', '224'),
  ('Ago07', '163'),
  ('Sep07', '242'),
  ('Oct07', '144'),
  ('Nov07', '245'),
  ('Dic07', '189'),
  ('Ene08', '147'),
  ('Feb08', '198'),
  ('Mar08', '264'),
  ('Abr08', '177'),
  ('May08', '253'),
  ('Jun08', '194'),
  ('Jul08', '221'),
  ('Ago08', '266'),
  ('Sep08', '255'),
  ('Oct08', '160'),
  ('Nov08', '158'),
  ('Dic08', '142'),
  ('Ene09', '82'),
  ('Feb09', '146'),
  ('Mar09', '128'),
  ('Abr09', '146'),
  ('May09', '167'),
  ('Jun09', '176'),
  ('Jul09', '190'),
  ('Ago09', '212'),
  ('Sep09', '257'),
  ('Oct09', '255'),
  ('Nov09', '328'),
  ('Dic09', '306'),
  ('Ene10', '251'),
  ('Feb10', '256'),
  ('Mar10', '317'),
  ('Abr10', '287'),
  ('May10', '192'),
  ('Jun10', '300'),
  ('Jul10', '285'),
  ('Ago10', '301'),
  ('Sep10', '324'),
  ('Oct10', '303'),
  ('Nov10', '381'),
  ('Dic10', '339'),
  ('Ene11', '343'),
  ('Feb11', '418'),
  ('Mar11', '442'),
  ('Abr11', '328'),
  ('May11', '500'),
  ('Jun11', '436'),
  ('Jul11', '337'),
  ('Ago11', '411'),
  ('Sep11', '393'),
  ('Oct11', '298'),
  ('Nov11', '301'),
  ('Dic11', '331'),
  ('Ene12', '299'),
  ('Feb12', '243'),
  ('Mar12', '440'),
  ('Abr12', '221'),
  ('May12', '383'),
  ('Jun12', '350'),
  ('Jul12', '231'),
  ('Ago12', '335'),
  ('Sep12', '395'),
  ('Oct12', '274'),
  ('Nov12', '252'),
  ('Dic12', '365'),
  ('Ene13', '297'),
  ('Feb13', '202'),
  ('Mar13', '341'),
  ('Abr13', '261'),
  ('May13', '364'),
  ('Jun13', '303'),
  ('Jul13', '293'),
  ('Ago13', '324'),
  ('Sep13', '314'),
  ('Oct13', '324'),
  ('Nov13', '271'),
  ('Dic13', '421'),
  ('Ene14', '280'),
  ('Feb14', '189'),
  ('Mar14', '288'),
  ('Abr14', '217'),
  ('May14', '310'),
  ('Jun14', '273'),
  ('Jul14', '256'),
  ('Ago14', '280'),
  ('Sep14', '219'),
  ('Oct14', '248'),
  ('Nov14', '236'),
  ('Dic14', '275'),
  ('Ene15', '217'),
  ('Feb15', '184'),
  ('Mar15', '233'),
  ('Abr15', '218'),
  ('May15', '166'),
  ('Jun15', '265'),
  ('Jul15', '224'),
  ('Ago15', '235'),
  ('Sep15', '300'),
  ('Oct15', '292'),
  ('Nov15', '344'),
  ('Dic15', '418'),
  ('Ene16', '278'),
  ('Feb16', '330'),
  ('Mar16', '384'),
  ('Abr16', '381'),
  ('May16', '373'),
  ('Jun16', '326'),
  ('Jul16', '395'),
  ('Ago16', '403'),
  ('Sep16', '348'),
  ('Oct16', '406'),
  ('Nov16', '384'),
  ('Dic16', '419'),
  ('Ene17', '346'),
  ('Feb17', '358'),
  ('Mar17', '409'),
  ('Abr17', '389'),
  ('May17', '376'),
  ('Jun17', '455'),
  ('Jul17', '358'),
  ('Ago17', '466'),
  ('Sep17', '522'),
  ('Oct17', '434'),
  ('Nov17', '456'),
  ('Dic17', '502'),
  ('Ene18', '459'),
  ('Feb18', '343'),
  ('Mar18', '531'),
  ('Abr18', '416'),
  ('May18', '455'),
  ('Jun18', '509'),
  ('Jul18', '391'),
  ('Ago18', '443'),
  ('Sep18', '439'),
  ('Oct18', '348'),
  ('Nov18', '453'),
  ('Dic18', '447'),
  ('Ene19', '355'),
  ('Feb19', '419'),
  ('Mar19', '460'),
  ('Abr19', '437'),
  ('May19', '323'),
  ('Jun19', '402'),
  ('Jul19', '329'),
  ('Ago19', '278'),
  ('Sep19', '377'),
  ('Oct19', '410'),
  ('Nov19', '451'),
  ('Dic19', '387'),
  ('Ene20', '321'),
  ('Feb20', '301'),
  ('Mar20', '244'),
  ('Abr20', '134'),
  ('May20', '238'),
  ('Jun20', '293'),
  ('Jul20', '301'),
  ('Ago20', '294'),
  ('Sep20', '415'),
  ('Oct20', '418'),
  ('Nov20', '345'),
  ('Dic20', '474'),
  ('Ene21', '379'),
  ('Feb21', '331'),
  ('Mar21', '443'),
  ('Abr21', '460'),
  ('May21', '401'),
  ('Jun21', '377'),
  ('Jul21', '480'),
  ('Ago21', '502'),
  ('Sep21', '603'),
  ('Oct21', '530'),
  ('Nov21', '396'),
  ('Dic21', '587'),
  ('Ene22', '541'),
  ('Feb22', '485'),
  ('Mar22', '548'),
  ('Abr22', '425'),
  ('May22', '607'),
  ('Jun22', '538'),
  ('Jul22', '440'),
  ('Ago22', '369'),
  ('Sep22', '511'),
  ('Oct22', '517'),
  ('Nov22', '421'),
  ('Dic22', '548')],
 'Ayacucho': [('Ene05', '0'),
  ('Feb05', '0'),
  ('Mar05', '0'),
  ('Abr05', '0'),
  ('May05', '0'),
  ('Jun05', '0'),
  ('Jul05', '1'),
  ('Ago05', '0'),
  ('Sep05', '0'),
  ('Oct05', '0'),
  ('Nov05', '0'),
  ('Dic05', '0'),
  ('Ene06', '0'),
  ('Feb06', '0'),
  ('Mar06', '0'),
  ('Abr06', '5'),
  ('May06', '0'),
  ('Jun06', '1'),
  ('Jul06', '1'),
  ('Ago06', '3'),
  ('Sep06', '3'),
  ('Oct06', '0'),
  ('Nov06', '0'),
  ('Dic06', '3'),
  ('Ene07', '4'),
  ('Feb07', '8'),
  ('Mar07', '0'),
  ('Abr07', '4'),
  ('May07', '4'),
  ('Jun07', '1'),
  ('Jul07', '1'),
  ('Ago07', '6'),
  ('Sep07', '7'),
  ('Oct07', '2'),
  ('Nov07', '6'),
  ('Dic07', '3'),
  ('Ene08', '12'),
  ('Feb08', '6'),
  ('Mar08', '3'),
  ('Abr08', '6'),
  ('May08', '3'),
  ('Jun08', '2'),
  ('Jul08', '14'),
  ('Ago08', '4'),
  ('Sep08', '12'),
  ('Oct08', '6'),
  ('Nov08', '4'),
  ('Dic08', '1'),
  ('Ene09', '1'),
  ('Feb09', '4'),
  ('Mar09', '4'),
  ('Abr09', '1'),
  ('May09', '7'),
  ('Jun09', '3'),
  ('Jul09', '3'),
  ('Ago09', '3'),
  ('Sep09', '2'),
  ('Oct09', '13'),
  ('Nov09', '5'),
  ('Dic09', '7'),
  ('Ene10', '8'),
  ('Feb10', '3'),
  ('Mar10', '11'),
  ('Abr10', '4'),
  ('May10', '5'),
  ('Jun10', '15'),
  ('Jul10', '8'),
  ('Ago10', '11'),
  ('Sep10', '10'),
  ('Oct10', '7'),
  ('Nov10', '13'),
  ('Dic10', '8'),
  ('Ene11', '10'),
  ('Feb11', '10'),
  ('Mar11', '9'),
  ('Abr11', '10'),
  ('May11', '16'),
  ('Jun11', '8'),
  ('Jul11', '11'),
  ('Ago11', '12'),
  ('Sep11', '15'),
  ('Oct11', '8'),
  ('Nov11', '13'),
  ('Dic11', '38'),
  ('Ene12', '12'),
  ('Feb12', '32'),
  ('Mar12', '17'),
  ('Abr12', '14'),
  ('May12', '8'),
  ('Jun12', '15'),
  ('Jul12', '17'),
  ('Ago12', '18'),
  ('Sep12', '13'),
  ('Oct12', '12'),
  ('Nov12', '12'),
  ('Dic12', '21'),
  ('Ene13', '11'),
  ('Feb13', '11'),
  ('Mar13', '13'),
  ('Abr13', '12'),
  ('May13', '15'),
  ('Jun13', '11'),
  ('Jul13', '13'),
  ('Ago13', '19'),
  ('Sep13', '20'),
  ('Oct13', '18'),
  ('Nov13', '23'),
  ('Dic13', '16'),
  ('Ene14', '11'),
  ('Feb14', '17'),
  ('Mar14', '26'),
  ('Abr14', '28'),
  ('May14', '16'),
  ('Jun14', '16'),
  ('Jul14', '25'),
  ('Ago14', '30'),
  ('Sep14', '22'),
  ('Oct14', '21'),
  ('Nov14', '19'),
  ('Dic14', '8'),
  ('Ene15', '18'),
  ('Feb15', '11'),
  ('Mar15', '33'),
  ('Abr15', '13'),
  ('May15', '15'),
  ('Jun15', '20'),
  ('Jul15', '28'),
  ('Ago15', '29'),
  ('Sep15', '25'),
  ('Oct15', '12'),
  ('Nov15', '13'),
  ('Dic15', '16'),
  ('Ene16', '10'),
  ('Feb16', '10'),
  ('Mar16', '26'),
  ('Abr16', '15'),
  ('May16', '33'),
  ('Jun16', '12'),
  ('Jul16', '19'),
  ('Ago16', '29'),
  ('Sep16', '33'),
  ('Oct16', '22'),
  ('Nov16', '20'),
  ('Dic16', '31'),
  ('Ene17', '17'),
  ('Feb17', '26'),
  ('Mar17', '16'),
  ('Abr17', '33'),
  ('May17', '23'),
  ('Jun17', '23'),
  ('Jul17', '21'),
  ('Ago17', '44'),
  ('Sep17', '23'),
  ('Oct17', '27'),
  ('Nov17', '30'),
  ('Dic17', '26'),
  ('Ene18', '26'),
  ('Feb18', '22'),
  ('Mar18', '23'),
  ('Abr18', '44'),
  ('May18', '22'),
  ('Jun18', '32'),
  ('Jul18', '13'),
  ('Ago18', '30'),
  ('Sep18', '27'),
  ('Oct18', '38'),
  ('Nov18', '39'),
  ('Dic18', '29'),
  ('Ene19', '42'),
  ('Feb19', '40'),
  ('Mar19', '40'),
  ('Abr19', '26'),
  ('May19', '20'),
  ('Jun19', '31'),
  ('Jul19', '21'),
  ('Ago19', '26'),
  ('Sep19', '23'),
  ('Oct19', '28'),
  ('Nov19', '19'),
  ('Dic19', '6'),
  ('Ene20', '50'),

In [45]:
df = pd.DataFrame(resultados)
df

,Amazonas,Ancash,Apurimac,Arequipa,Ayacucho,Cajamarca,Callao,Cusco,Huancavelica,Huánuco,...,Moquegua,Pasco,Piura,Puno,San Martín,Tacna,Tumbes,Ucayali,No registrado,Total
0,"(Ene05, 0)","(Ene05, 189)","(Ene05, 0)","(Ene05, 28)","(Ene05, 0)","(Ene05, 84)","(Ene05, 94)","(Ene05, 29)","(Ene05, 0)","(Ene05, 0)",...,"(Ene05, 170)","(Ene05, 11)","(Ene05, 64)","(Ene05, 4)","(Ene05, 4)","(Ene05, 72)","(Ene05, 4)","(Ene05, 1)","(Ene05, 5)","(Ene05, 1264)"
1,"(Feb05, 0)","(Feb05, 152)","(Feb05, 0)","(Feb05, 31)","(Feb05, 0)","(Feb05, 135)","(Feb05, 74)","(Feb05, 7)","(Feb05, 0)","(Feb05, 0)",...,"(Feb05, 100)","(Feb05, 18)","(Feb05, 69)","(Feb05, 6)","(Feb05, 1)","(Feb05, 40)","(Feb05, 6)","(Feb05, 2)","(Feb05, 4)","(Feb05, 1137)"
2,"(Mar05, 0)","(Mar05, 198)","(Mar05, 5)","(Mar05, 57)","(Mar05, 0)","(Mar05, 121)","(Mar05, 89)","(Mar05, 45)","(Mar05, 1)","(Mar05, 2)",...,"(Mar05, 109)","(Mar05, 54)","(Mar05, 61)","(Mar05, 7)","(Mar05, 0)","(Mar05, 53)","(Mar05, 5)","(Mar05, 2)","(Mar05, 5)","(Mar05, 1347)"
3,"(Abr05, 0)","(Abr05, 157)","(Abr05, 3)","(Abr05, 56)","(Abr05, 0)","(Abr05, 94)","(Abr05, 99)","(Abr05, 30)","(Abr05, 0)","(Abr05, 2)",...,"(Abr05, 171)","(Abr05, 32)","(Abr05, 55)","(Abr05, 6)","(Abr05, 3)","(Abr05, 27)","(Abr05, 6)","(Abr05, 2)","(Abr05, 6)","(Abr05, 1258)"
4,"(May05, 0)","(May05, 188)","(May05, 4)","(May05, 56)","(May05, 0)","(May05, 107)","(May05, 121)","(May05, 29)","(May05, 0)","(May05, 2)",...,"(May05, 123)","(May05, 16)","(May05, 76)","(May05, 6)","(May05, 3)","(May05, 34)","(May05, 7)","(May05, 3)","(May05, 6)","(May05, 1355)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,"(Ago22, 9)","(Ago22, 662)","(Ago22, 312)","(Ago22, 369)","(Ago22, 61)","(Ago22, 201)","(Ago22, 426)","(Ago22, 134)","(Ago22, 3)","(Ago22, 2)",...,"(Ago22, 303)","(Ago22, 30)","(Ago22, 205)","(Ago22, 154)","(Ago22, 20)","(Ago22, 29)","(Ago22, 15)","(Ago22, 9)","(Ago22, 213)","(Ago22, 5785)"
212,"(Sep22, 12)","(Sep22, 594)","(Sep22, 272)","(Sep22, 511)","(Sep22, 51)","(Sep22, 186)","(Sep22, 369)","(Sep22, 222)","(Sep22, 5)","(Sep22, 0)",...,"(Sep22, 261)","(Sep22, 37)","(Sep22, 230)","(Sep22, 165)","(Sep22, 20)","(Sep22, 45)","(Sep22, 10)","(Sep22, 3)","(Sep22, 234)","(Sep22, 5765)"
213,"(Oct22, 11)","(Oct22, 422)","(Oct22, 263)","(Oct22, 517)","(Oct22, 79)","(Oct22, 191)","(Oct22, 395)","(Oct22, 196)","(Oct22, 4)","(Oct22, 1)",...,"(Oct22, 271)","(Oct22, 87)","(Oct22, 358)","(Oct22, 165)","(Oct22, 22)","(Oct22, 29)","(Oct22, 10)","(Oct22, 9)","(Oct22, 233)","(Oct22, 5525)"
214,"(Nov22, 5)","(Nov22, 482)","(Nov22, 40)","(Nov22, 421)","(Nov22, 69)","(Nov22, 160)","(Nov22, 278)","(Nov22, 159)","(Nov22, 6)","(Nov22, 1)",...,"(Nov22, 531)","(Nov22, 40)","(Nov22, 419)","(Nov22, 108)","(Nov22, 18)","(Nov22, 61)","(Nov22, 10)","(Nov22, 14)","(Nov22, 211)","(Nov22, 5226)"
215,"(Dic22, 6)","(Dic22, 454)","(Dic22, 44)","(Dic22, 548)","(Dic22, 67)","(Dic22, 187)","(Dic22, 354)","(Dic22, 276)","(Dic22, 3)","(Dic22, 1)",...,"(Dic22, 598)","(Dic22, 74)","(Dic22, 582)","(Dic22, 123)","(Dic22, 14)","(Dic22, 67)","(Dic22, 8)","(Dic22, 14)","(Dic22, 235)","(Dic22, 6306)"

In [47]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import pandas as pd
import time
import os

def extraer_datos_bcrp(codigos_dict):
    """
    Extrae datos del BCRP para múltiples códigos
    
    Args:
        codigos_dict: Diccionario con formato {codigo: descripcion}
    
    Returns:
        Un diccionario con los datos extraídos por cada región
    """
    # Configuración del navegador
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')  # Opcional: ejecutar sin interfaz gráfica
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()
    
    resultados = {}
    
    try:
        for codigo, descripcion in codigos_dict.items():
            print(f"Procesando {descripcion} (código: {codigo})...")
            
            # Acceder directamente al enlace con el código proporcionado
            url = f"https://estadisticas.bcrp.gob.pe/estadisticas/series/mensuales/resultados/{codigo}/html"
            driver.get(url)
            
            try:
                # Esperar que la tabla cargue
                wait = WebDriverWait(driver, 10)
                wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'table.series')))
                
                # Extraer filas de la tabla
                rows = driver.find_elements(By.CSS_SELECTOR, 'table.series tbody tr')
                periodos = []
                valores = []
                
                for row in rows:
                    try:
                        periodo_elem = row.find_element(By.CSS_SELECTOR, 'td.periodo b')
                        dato_elem = row.find_element(By.CSS_SELECTOR, 'td.dato')
                        periodo = periodo_elem.text.strip()
                        dato = dato_elem.text.strip()
                        periodos.append(periodo)
                        valores.append(dato)
                    except NoSuchElementException:
                        continue  # Saltar filas sin datos
                
                # Guardamos los datos como un diccionario con dos listas (mejor para DataFrame)
                resultados[descripcion] = {
                    'periodos': periodos,
                    'valores': valores
                }
                print(f"✓ Datos extraídos correctamente para {descripcion}")
                
                # Pausa breve para no sobrecargar el servidor
                time.sleep(1)
                
            except TimeoutException:
                print(f"❌ Error: Timeout al cargar datos para {descripcion} (código: {codigo})")
                resultados[descripcion] = {'periodos': [], 'valores': []}
    
    except Exception as e:
        print(f"Error general: {str(e)}")
    
    finally:
        driver.quit()
        
    return resultados

def guardar_resultados(resultados, formato="csv"):
    """
    Guarda los resultados en archivos
    
    Args:
        resultados: Diccionario con los datos extraídos
        formato: 'csv' o 'excel'
    """
    # Crear directorio para resultados si no existe
    os.makedirs("resultados_bcrp", exist_ok=True)
    
    # Guardar cada región en un archivo separado
    for region, datos in resultados.items():
        periodos = datos.get('periodos', [])
        valores = datos.get('valores', [])
        
        if not periodos:
            print(f"No hay datos para guardar de {region}")
            continue
            
        df = pd.DataFrame({
            'Periodo': periodos,
            'Valor': valores
        })
        
        # Limpiar el nombre del archivo
        nombre_archivo = region.replace("/", "_").replace("\\", "_").strip()
        
        if formato == "csv":
            ruta = f"resultados_bcrp/{nombre_archivo}.csv"
            df.to_csv(ruta, index=False)
        elif formato == "excel":
            ruta = f"resultados_bcrp/{nombre_archivo}.xlsx"
            df.to_excel(ruta, index=False)
            
        print(f"Archivo guardado: {ruta}")
    
    # Crear un archivo consolidado con todos los datos
    all_data = {
        'Region': [],
        'Periodo': [],
        'Valor': []
    }
    
    for region, datos in resultados.items():
        periodos = datos.get('periodos', [])
        valores = datos.get('valores', [])
        
        if periodos:
            all_data['Region'].extend([region] * len(periodos))
            all_data['Periodo'].extend(periodos)
            all_data['Valor'].extend(valores)
    
    if all_data['Region']:
        df_consolidado = pd.DataFrame(all_data)
        
        if formato == "csv":
            df_consolidado.to_csv("resultados_bcrp/consolidado.csv", index=False)
        elif formato == "excel":
            df_consolidado.to_excel("resultados_bcrp/consolidado.xlsx", index=False)
            
        print(f"Archivo consolidado guardado en resultados_bcrp/consolidado.{formato}")

# Códigos y descripciones proporcionados
codigos_bcrp = {
    "RD38085BM": "Amazonas",
    "RD38086BM": "Ancash",
    "RD38087BM": "Apurimac",
    "RD38088BM": "Arequipa",
    "RD38089BM": "Ayacucho",
    "RD38090BM": "Cajamarca",
    "RD38091BM": "Callao",
    "RD38092BM": "Cusco",
    "RD38093BM": "Huancavelica",
    "RD38094BM": "Huánuco",
    "RD38095BM": "Ica",
    "RD38096BM": "Junín",
    "RD38097BM": "La Libertad",
    "RD38098BM": "Lambayeque",
    "RD38099BM": "Lima",
    "RD38100BM": "Loreto",
    "RD38101BM": "Madre de Dios",
    "RD38102BM": "Moquegua",
    "RD38103BM": "Pasco",
    "RD38104BM": "Piura",
    "RD38105BM": "Puno",
    "RD38106BM": "San Martín",
    "RD38107BM": "Tacna",
    "RD38108BM": "Tumbes",
    "RD38109BM": "Ucayali",
    "RD38110BM": "No registrado",
    "RD38111BM": "Total"
}

# Ejecutar el script
if __name__ == "__main__":
    print("Iniciando extracción de datos del BCRP...")
    resultados = extraer_datos_bcrp(codigos_bcrp)
    
    # Guardar resultados en CSV (puedes cambiar a "excel" si prefieres)
    guardar_resultados(resultados, formato="csv")
    
    print("Proceso completado.")

Iniciando extracción de datos del BCRP...
Procesando Amazonas (código: RD38085BM)...
✓ Datos extraídos correctamente para Amazonas
Procesando Ancash (código: RD38086BM)...
✓ Datos extraídos correctamente para Ancash
Procesando Apurimac (código: RD38087BM)...
✓ Datos extraídos correctamente para Apurimac
Procesando Arequipa (código: RD38088BM)...
✓ Datos extraídos correctamente para Arequipa
Procesando Ayacucho (código: RD38089BM)...
✓ Datos extraídos correctamente para Ayacucho
Procesando Cajamarca (código: RD38090BM)...
✓ Datos extraídos correctamente para Cajamarca
Procesando Callao (código: RD38091BM)...
✓ Datos extraídos correctamente para Callao
Procesando Cusco (código: RD38092BM)...
✓ Datos extraídos correctamente para Cusco
Procesando Huancavelica (código: RD38093BM)...
✓ Datos extraídos correctamente para Huancavelica
Procesando Huánuco (código: RD38094BM)...
✓ Datos extraídos correctamente para Huánuco
Procesando Ica (código: RD38095BM)...
✓ Datos extraídos correctamente para Ica
Procesando Junín (código: RD38096BM)...
✓ Datos extraídos correctamente para Junín
Procesando La Libertad (código: RD38097BM)...
✓ Datos extraídos correctamente para La Libertad
Procesando Lambayeque (código: RD38098BM)...
✓ Datos extraídos correctamente para Lambayeque
Procesando Lima (código: RD38099BM)...
✓ Datos extraídos correctamente para Lima
Procesando Loreto (código: RD38100BM)...
✓ Datos extraídos correctamente para Loreto
Procesando Madre de Dios (código: RD38101BM)...
✓ Datos extraídos correctamente para Madre de Dios
Procesando Moquegua (código: RD38102BM)...
✓ Datos extraídos correctamente para Moquegua
Procesando Pasco (código: RD38103BM)...
✓ Datos extraídos correctamente para Pasco
Procesando Piura (código: RD38104BM)...
✓ Datos extraídos correctamente para Piura
Procesando Puno (código: RD38105BM)...
✓ Datos extraídos correctamente para Puno
Procesando San Martín (código: RD38106BM)...
✓ Datos extraídos correctamente para San Martín
Procesando Tacna (código: RD38107BM)...
✓ Datos extraídos correctamente para Tacna
Procesando Tumbes (código: RD38108BM)...
✓ Datos extraídos correctamente para Tumbes
Procesando Ucayali (código: RD38109BM)...
✓ Datos extraídos correctamente para Ucayali
Procesando No registrado (código: RD38110BM)...
✓ Datos extraídos correctamente para No registrado
Procesando Total (código: RD38111BM)...
✓ Datos extraídos correctamente para Total
Archivo guardado: resultados_bcrp/Amazonas.csv
Archivo guardado: resultados_bcrp/Ancash.csv
Archivo guardado: resultados_bcrp/Apurimac.csv
Archivo guardado: resultados_bcrp/Arequipa.csv
Archivo guardado: resultados_bcrp/Ayacucho.csv
Archivo guardado: resultados_bcrp/Cajamarca.csv
Archivo guardado: resultados_bcrp/Callao.csv
Archivo guardado: resultados_bcrp/Cusco.csv
Archivo guardado: resultados_bcrp/Huancavelica.csv
Archivo guardado: resultados_bcrp/Huánuco.csv
Archivo guardado: resultados_bcrp/Ica.csv
Archivo guardado: resultados_bcrp/Junín.csv
Archivo guardado: resultados_bcrp/La Libertad.csv
Archivo guardado: resultados_bcrp/Lambayeque.csv
Archivo guardado: resultados_bcrp/Lima.csv
Archivo guardado: resultados_bcrp/Loreto.csv
Archivo guardado: resultados_bcrp/Madre de Dios.csv
Archivo guardado: resultados_bcrp/Moquegua.csv
Archivo guardado: resultados_bcrp/Pasco.csv
Archivo guardado: resultados_bcrp/Piura.csv
Archivo guardado: resultados_bcrp/Puno.csv
Archivo guardado: resultados_bcrp/San Martín.csv
Archivo guardado: resultados_bcrp/Tacna.csv
Archivo guardado: resultados_bcrp/Tumbes.csv
Archivo guardado: resultados_bcrp/Ucayali.csv
Archivo guardado: resultados_bcrp/No registrado.csv
Archivo guardado: resultados_bcrp/Total.csv
Archivo consolidado guardado en resultados_bcrp/consolidado.csv
Proceso completado.

In [50]:
df = pd.DataFrame(resultados)
df

,Amazonas,Ancash,Apurimac,Arequipa,Ayacucho,Cajamarca,Callao,Cusco,Huancavelica,Huánuco,...,Moquegua,Pasco,Piura,Puno,San Martín,Tacna,Tumbes,Ucayali,No registrado,Total
periodos,"[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...",...,"[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul...","[Ene05, Feb05, Mar05, Abr05, May05, Jun05, Jul..."
valores,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, ...","[189, 152, 198, 157, 188, 231, 241, 209, 215, ...","[0, 0, 5, 3, 4, 0, 3, 3, 4, 3, 0, 7, 0, 0, 21,...","[28, 31, 57, 56, 56, 41, 59, 51, 48, 22, 82, 5...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[84, 135, 121, 94, 107, 119, 99, 116, 134, 148...","[94, 74, 89, 99, 121, 113, 117, 124, 95, 133, ...","[29, 7, 45, 30, 29, 15, 12, 34, 44, 18, 39, 52...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 1, ...","[0, 0, 2, 2, 2, 8, 0, 5, 1, 1, 6, 6, 0, 2, 0, ...",...,"[170, 100, 109, 171, 123, 99, 156, 120, 153, 1...","[11, 18, 54, 32, 16, 41, 22, 38, 22, 24, 30, 5...","[64, 69, 61, 55, 76, 41, 68, 91, 73, 39, 79, 7...","[4, 6, 7, 6, 6, 7, 5, 10, 9, 11, 9, 10, 8, 9, ...","[4, 1, 0, 3, 3, 4, 4, 3, 6, 3, 5, 6, 5, 1, 1, ...","[72, 40, 53, 27, 34, 27, 66, 32, 43, 92, 28, 7...","[4, 6, 5, 6, 7, 8, 5, 4, 4, 5, 7, 4, 6, 5, 6, ...","[1, 2, 2, 2, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2, 2, ...","[5, 4, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 1, 1, 0, ...","[1264, 1137, 1347, 1258, 1355, 1422, 1558, 149..."